AWSTemplateFormatVersion: 2010-09-09
Resources:
  VpcTreinamento:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "172.16.0.0/16"
      Tags:
        - Key: "Name"
          Value: "VpcTreinamento"
  SubnetPublicaB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1b"
      CidrBlock: "172.16.0.0/24"
      MapPublicIpOnLaunch: True
      Tags:
        - Key: "Name"
          Value: "SubnetPublicaB"
      VpcId:
        Ref: VpcTreinamento
  SubnetPublicaC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1b"
      CidrBlock: "172.16.1.0/24"
      MapPublicIpOnLaunch: True
      Tags:
        - Key: "Name"
          Value: "SubnetPublicaC"
      VpcId:
        Ref: VpcTreinamento
  SubnetPrivadaB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1b"
      CidrBlock: "172.16.2.0/24"
      MapPublicIpOnLaunch: False
      Tags:
        - Key: "Name"
          Value: "SubnetPrivadaB"
      VpcId:
        Ref: VpcTreinamento
  SubnetPrivadaC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1b"
      CidrBlock: "172.16.3.0/24"
      MapPublicIpOnLaunch: False
      Tags:
        - Key: "Name"
          Value: "SubnetPrivadaC"
      VpcId:
        Ref: VpcTreinamento
  RouteTablePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VpcTreinamento
      Tags:
        - Key: Name
          Value: "RouteTablePublic"
            


        
