AWSTemplateFormatVersion: 2010-09-09
Resources:
  VpcTreinamento:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "172.16.0.0/16"
      Tags:
        - Key: "Name"
          Value: "VpcTreinamento"
  SubnetPublicB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1b"
      CidrBlock: "172.16.0.0/24"
      MapPublicIpOnLaunch: True
      Tags:
        - Key: "Name"
          Value: "SubnetPublicB"
      VpcId:
        Ref: VpcTreinamento
  SubnetPublicC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1b"
      CidrBlock: "172.16.1.0/24"
      MapPublicIpOnLaunch: True
      Tags:
        - Key: "Name"
          Value: "SubnetPublicC"
      VpcId:
        Ref: VpcTreinamento
  SubnetPrivateB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1b"
      CidrBlock: "172.16.2.0/24"
      MapPublicIpOnLaunch: False
      Tags:
        - Key: "Name"
          Value: "SubnetPrivateB"
      VpcId:
        Ref: VpcTreinamento
  SubnetPrivateC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1b"
      CidrBlock: "172.16.3.0/24"
      MapPublicIpOnLaunch: False
      Tags:
        - Key: "Name"
          Value: "SubnetPrivateC"
      VpcId:
        Ref: VpcTreinamento
  RouteTablePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VpcTreinamento
      Tags:
        - Key: Name
          Value: "RouteTablePublic"
  RouteTablePrivateB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VpcTreinamento
      Tags:
        - Key: Name
          Value: "RouteTablePrivateB"
  RouteTablePrivateC:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VpcTreinamento
      Tags:
        - Key: Name
          Value: "RouteTablePrivateC"
  RouteTableAssociationPublicB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId:
        Ref: RouteTablePublic
      SubnetId:
        Ref: SubnetPublicB        
  RouteTableAssociationPublicC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId:
        Ref: RouteTablePublic
      SubnetId:
        Ref: SubnetPublicC        
  RouteTableAssociationPrivateB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId:
        Ref: RouteTablePrivateB
      SubnetId:
        Ref: SubnetPrivateB    
  RouteTableAssociationPrivateC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId:
        Ref: RouteTablePrivateC
      SubnetId:
        Ref: SubnetPrivateC
  ElasticIPB:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  ElasticIPC:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  NatGatewayB:
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId:
        Ref: ElasticIPB
      SubnetId:
        Ref: SubnetPrivateB
      Tags: 
        - Key: Name
          Value: "NatGatewayB"
    DependsOn: ElasticIPB
  NatGatewayC:
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId:
        Ref: ElasticIPC
      SubnetId:
        Ref: SubnetPrivateC
      Tags: 
        - Key: Name
          Value: "NatGatewayC"
    DependsOn: ElasticIPC

            


        
